// src/components/authScreens/Register.vue
<template>
  <div class="flex flex-col min-h-screen bg-gray-50">
    <div class="flex   justify-center items-center  flex-wrap w-full login-container">
      <div class="flex justify-center items-center  w-full  p-6 middle-container">
        <!-- Register form -->
        <div class="w-full max-w-lg bg-white shadow-lg  rounded-lg p-8">
          <div class="w-full text-center mb-6">
            <h2 class="text-2xl font-bold text-gray-800">Register</h2>
            <p class="text-sm text-gray-600 mt-2">Create your account below</p>
          </div>
          <form
            @submit.prevent="validatePassword"
            class="space-y-6"
          >
            <div>
              <label
                for="firstName"
                class="block text-sm font-medium text-gray-700"
              >
                First Name
              </label>
              <input
                id="firstName"
                v-model="firstName"
                type="text"
                class="mt-1 w-full border border-gray-300 rounded-md p-3 focus:ring-blue-500 focus:border-blue-500"
                placeholder="Enter your first name"
                required
              />
            </div>
            <div>
              <label
                for="lastName"
                class="block text-sm font-medium text-gray-700"
              >
                Last Name
              </label>
              <input
                id="lastName"
                v-model="lastName"
                type="text"
                class="mt-1 w-full border border-gray-300 rounded-md p-3 focus:ring-blue-500 focus:border-blue-500"
                placeholder="Enter your last name"
                required
              />
            </div>
            <div>
              <label
                for="telephone"
                class="block text-sm font-medium text-gray-700"
              >
                Telephone
              </label>
              <input
                id="telephone"
                v-model="telephone"
                type="text"
                class="mt-1 w-full border border-gray-300 rounded-md p-3 focus:ring-blue-500 focus:border-blue-500"
                placeholder="Enter your telephone number"
                required
                @input="validateTelephone"
              />
              <p
                v-if="telephoneError"
                class="text-red-500 text-sm mt-1"
              >
                Please enter a valid telephone number.
              </p>
            </div>

             <div>
              <label
                for="password"
                class="block text-sm font-medium text-gray-700"
              >
                User Role
              </label>
              <select
                class="border rounded-md"
                v-model="selectedRole"
                name="Role"
                id="Role"
                required
              >
                <option value="">Role</option>
                <option value="user">User</option>
                <option value="Admin">Admin</option>

              </select>
            </div>

            <div>
              <label
                for="password"
                class="block text-sm font-medium text-gray-700"
              >
                Password
              </label>
              <input
                id="password"
                v-model="password"
                type="password"
                class="mt-1 w-full border border-gray-300 rounded-md p-3 focus:ring-blue-500 focus:border-blue-500"
                placeholder="Enter your password"
                required
              />
            </div>

           

            <div>
              <label
                for="confirmPassword"
                class="block text-sm font-medium text-gray-700"
              >
                Confirm Password
              </label>
              <input
                id="confirmPassword"
                v-model="confirmPassword"
                type="password"
                class="mt-1 w-full border border-gray-300 rounded-md p-3 focus:ring-blue-500 focus:border-blue-500"
                placeholder="Re-enter your password"
                required
              />
              <p
                v-if="passwordMismatch"
                class="text-red-500 text-sm mt-1"
              >
                Passwords do not match.
              </p>
            </div>
            <button
              type="submit"
              :disabled="loading"
              class="w-full bg-blue-500 text-white py-3 rounded-md hover:bg-blue-600 focus:outline-none focus:ring-2 focus:ring-blue-300 transition duration-300 disabled:bg-blue-300"
            >
              <span v-if="loading">
                ...
              </span>
              <span v-else>Register</span>
            </button>
          </form>
          <p class="py-4 text-center text-sm">
            Already have an account?
            <router-link
              to="/login"
              class="text-blue-500 font-semibold hover:underline"
            >
              Login here
            </router-link>
          </p>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import axios from "axios";
import { mapState, mapActions } from "vuex";
export default {
  data() {
    return {
      firstName: "",
      lastName: "",
      telephone: "",
      password: "",
      confirmPassword: "",
      telephoneError: false,
      passwordMismatch: false,
      loading: false,
      selectedRole: null,
    };
  },
   computed: {
    ...mapState(["user"]),
  },
  methods: {
    validateTelephone() {
      const numericRegex = /^[0-9]*$/;
      // Show error if not numeric
      this.telephoneError = !numericRegex.test(this.telephone);
    },
    validatePassword() {
      if (this.password !== this.confirmPassword) {
        // Show mismatch error
        this.passwordMismatch = true;
        return;
      }
      this.passwordMismatch = false;
      // Proceed with registration
      this.register();
    },
   async register() {
  this.loading = true;
  try {
    const registerUserInfo = {
      id: this.password, 
      firstName: this.firstName,
      lastName: this.lastName,
      telephone: this.telephone,
      password: this.password,
      selectedRole: this.selectedRole,
      token: `admin-token-12345-${this.selectedRole}-${this.password}`,
    };
    
    // Retrieve existing users from localStorage
    const existingUsers = JSON.parse(localStorage.getItem("user-registerUserInfo")) || [];
    
    // Add the new user to the existing list
    existingUsers.push(registerUserInfo);
    
    // Save updated user list back to localStorage
    localStorage.setItem("user-registerUserInfo", JSON.stringify(existingUsers));
    
    alert("Registration successful!");
    this.$router.push("/login");
  } catch (error) {
    alert("Registration failed!");
  } finally {
    this.loading = false;
  }
}

  },
};
</script>

<style scoped>
.login-container {
  padding: 1rem;
}

.middle-container {
  max-width: 600px;
}

button:disabled {
  cursor: not-allowed;
}
</style>

// src/components/screens/Register.jsx
import React, { useState } from "react";
import { Eye, EyeOff } from "lucide-react";
import { useNavigate } from "react-router-dom";
import axios from "axios";
import { ToastContainer, toast } from 'react-toastify';
import { Loader, ArrowRight, Copy, Check, AlertCircle, X } from 'lucide-react';
const apiBaseUrl = import.meta.env.VITE_APP_API_URL;
const RegisterPage = ({ closeToast, toastProps }) => {
 

  const [formData, setFormData] = useState({
    fullName: "",
    email: "",
    password: "",
    confirmPassword: "",
  });

  const [loading, setLoading] = useState(false);
  const [errors, setErrors] = useState({});
  const [showPassword, setShowPassword] = useState(false);
  const [showConfirmPassword, setShowConfirmPassword] = useState(false);

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData({
      ...formData,
      [name]: value,
    });

    // Clear error when user starts typing
    if (errors[name]) {
      setErrors({
        ...errors,
        [name]: "",
      });
    }
  };

  const validateForm = () => {
    const newErrors = {};

    // Full Name validation
    if (!formData.fullName.trim()) {
      newErrors.fullName = "Full name is required";
    }

    // Email validation
    if (!formData.email) {
      newErrors.email = "Email is required";
    } else if (!/\S+@\S+\.\S+/.test(formData.email)) {
      newErrors.email = "Email is invalid";
    }

    // Password validation
    if (!formData.password) {
      newErrors.password = "Password is required";
    } else if (formData.password.length < 6) {
      newErrors.password = "Password must be at least 6 characters";
    }

    // Confirm Password validation
    if (!formData.confirmPassword) {
      newErrors.confirmPassword = "Please confirm your password";
    } else if (formData.password !== formData.confirmPassword) {
      newErrors.confirmPassword = "Passwords do not match";
    }

    return newErrors;
  };

  // Handle rgister form submission
  const handleSubmit = async (e) => {
    e.preventDefault();
    setLoading(true);
    const formErrors = validateForm();

    if (Object.keys(formErrors).length === 0) {
      try {
        const response = await axios.post(
          `${apiBaseUrl}/auth/register`,
          {
            username: formData.fullName,
            email: formData.email,
            password: formData.password,
          }
        );

      

        console.log(response);
        toast.success("Registration successful! Please log in");
      
        window.location.replace("/login");
        setLoading(false);
        setFormData({
          fullName: "",
          email: "",
          password: "",
          confirmPassword: "",
        });

        setErrors({});
      

      } catch (error) {
        console.error("Registration error:", error);
        setLoading(false);
        setErrors({ apiError: error.message });
        toast.error(error.response.data.message);

        setLoading(false);
      }
    } else {
      setLoading(false);
      setErrors(formErrors);
    }
  };

  return (
    <div className="min-h-screen flex items-center justify-center bg-gray-100">
      <div className="bg-white p-8 rounded-lg shadow-md w-full max-w-md">
        <h2 className="text-2xl font-bold text-center text-blue-600 mb-6">
          Create an Account
        </h2>
        <form onSubmit={handleSubmit}>
          <div className="mb-4">
            <label
              htmlFor="fullName"
              className="block text-gray-700 text-sm font-medium mb-2"
            >
              Full Name
            </label>
            <input
              type="text"
              id="fullName"
              name="fullName"
              value={formData.fullName}
              onChange={handleChange}
              className={`w-full px-3 py-2 border rounded-lg focus:outline-none focus:ring-2 ${
                errors.fullName
                  ? "border-red-500 focus:ring-red-200"
                  : "border-gray-300 focus:ring-blue-200"
              }`}
              placeholder="Enter your full name"
            />
            {errors.fullName && (
              <p className="text-red-500 text-xs mt-1">{errors.fullName}</p>
            )}
          </div>

          <div className="mb-4">
            <label
              htmlFor="email"
              className="block text-gray-700 text-sm font-medium mb-2"
            >
              Email Address
            </label>
            <input
              type="text"
              id="email"
              name="email"
              value={formData.email}
              onChange={handleChange}
              className={`w-full px-3 py-2 border rounded-lg focus:outline-none focus:ring-2 ${
                errors.email
                  ? "border-red-500 focus:ring-red-200"
                  : "border-gray-300 focus:ring-blue-200"
              }`}
              placeholder="Enter your email"
            />
            {errors.email && (
              <p className="text-red-500 text-xs mt-1">{errors.email}</p>
            )}
          </div>

          <div className="mb-4">
            <label
              htmlFor="password"
              className="block text-gray-700 text-sm font-medium mb-2"
            >
              Password
            </label>
            <div className="relative">
              <input
                type={showPassword ? "text" : "password"}
                id="password"
                name="password"
                value={formData.password}
                onChange={handleChange}
                className={`w-full px-3 py-2 border rounded-lg focus:outline-none focus:ring-2 ${
                  errors.password
                    ? "border-red-500 focus:ring-red-200"
                    : "border-gray-300 focus:ring-blue-200"
                }`}
                placeholder="Create a password"
              />
              <button
                type="button"
                onClick={() => setShowPassword(!showPassword)}
                className="absolute inset-y-0 right-0 pr-3 flex items-center"
              >
                {showPassword ? (
                  <EyeOff size={20} className="text-gray-500" />
                ) : (
                  <Eye size={20} className="text-gray-500" />
                )}
              </button>
            </div>
            {errors.password && (
              <p className="text-red-500 text-xs mt-1">{errors.password}</p>
            )}
          </div>

          <div className="mb-6">
            <label
              htmlFor="confirmPassword"
              className="block text-gray-700 text-sm font-medium mb-2"
            >
              Confirm Password
            </label>
            <div className="relative">
              <input
                type={showConfirmPassword ? "text" : "password"}
                id="confirmPassword"
                name="confirmPassword"
                value={formData.confirmPassword}
                onChange={handleChange}
                className={`w-full px-3 py-2 border rounded-lg focus:outline-none focus:ring-2 ${
                  errors.confirmPassword
                    ? "border-red-500 focus:ring-red-200"
                    : "border-gray-300 focus:ring-blue-200"
                }`}
                placeholder="Confirm your password"
              />
              <button
                type="button"
                onClick={() => setShowConfirmPassword(!showConfirmPassword)}
                className="absolute inset-y-0 right-0 pr-3 flex items-center"
              >
                {showConfirmPassword ? (
                  <EyeOff size={20} className="text-gray-500" />
                ) : (
                  <Eye size={20} className="text-gray-500" />
                )}
              </button>
            </div>
            {errors.confirmPassword && (
              <p className="text-red-500 text-xs mt-1">
                {errors.confirmPassword}
              </p>
            )}
          </div>

          <button
            type="submit"
            className="w-full bg-blue-600 text-white py-2 px-4 rounded-lg hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 disabled:bg-gray-400 disabled:cursor-not-allowed"
            disabled={loading}
          >
            {loading ? (
              <div className="flex items-center justify-center">
                 <Loader className="animate-spin mr-2" size={24} />
              </div>
            ) : (
              "Create Account"
            )}
          </button>

        </form>


        <div className="mt-6 text-center">
          <p className="text-sm text-gray-600">
            Already have an account ? {" "}
            <a href="/login" className="text-blue-600 hover:underline">
              Sign in
            </a>
          </p>
        </div>

      </div>
    </div>
  );
};

export default RegisterPage;
